--- source
--https://www.ejmastnak.com/tutorials/vim-latex/vimtex/
--https://jdhao.github.io/2019/03/26/nvim_latex_write_preview/
--
--Useful help sections
--:help vimtex-default-mappings - all vimtex mappings.
